### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by snoopyh42** [riade3788/TagMate#1]
Windows 11 Version 23H2 OS Build 22631.3672
Microsoft Defender 102.2405.17006.0
Google Chrome 125.0.6422.113 (Likely unrelated to this issue)

After downloading the .rar release, Windows Defender detected this package as containing a Trojan and blocked it.

**Comment by riade3788** [comment]
get a proper antivirus. I checked the rar file and the problem is 100% on your end. The app is safe 

Also you can always compile the code to make your app

**Comment by riade3788** [comment]
https://gridinsoft.com/online-virus-scanner/id/6676a2f0c91b64d835b75ad701352c6f798b346974d69ff2da950e0f5eece334

**Comment by riade3788** [comment]
Some antiviruses can sometimes flag newly created executable files as potential threats, even when they are harmless. This is because the antivirus software is trying to protect the computer from unknown executables that might carry harmful payloads. Temporarily disabling your antivirus can help in such situations
